name: uxservices-web-react-appshell-template
description: Stack Shell for micro frontend React
types:
  - app-template
tags:
  - "orange-stackfront-web-shell-scaffold"
inputs:
  - label: "Project name(must not have spaces and be lowercase)"
    type: text
    name: "project_name"
    global: true
    default: "stackfront_web_shell"
